name: CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node: ["14", "16", "18"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Upgrade NPM
        run: npm install -g pnpm

      - name: Yarn install 
        uses: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test --ci --coverage --maxWorkers=2

      - name: Build
        run: pnpm build
